### ISSUE TITLE
TypeError: global.backend.get_cursor_tracker is not a function

### ISSUE THREAD

**Issue by danielschwab** [mechtifs/wiggle#18]
In Wayland with GNOME 46 I get the this error

**Comment by fasdalf** [comment]
Same here for gnome 46 on X11

**Comment by craverii** [comment]
Error message:
TypeError: global.backend.get_cursor_tracker is not a function

System details:
# System Details Report
---

## Report details
- **Date generated:**                              2025-03-31 14:44:36

## Hardware Information:
- **Hardware Model:**                              Gigabyte Technology Co., Ltd. Z790 GAMING PLUS AX
- **Memory:**                                      32.0 GiB
- **Processor:**                                   Intel® Core™ i7-14700 × 28
- **Graphics:**                                    NVIDIA GeForce RTX™ 4060 Ti
- **Graphics 1:**                                  NVIDIA GeForce RTX™ 4060 Ti
- **Disk Capacity:**                               3.0 TB

## Software Information:
- **Firmware Version:**                            F2
- **OS Name:**                                     Ubuntu 24.04.2 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            X11
- **Kernel Version:**                              Linux 6.11.0-21-generic

**Comment by CraigFoote** [comment]
I'm getting the same error on GNOME 47 on Ubuntu 24.10 but it works fine on GNOME 48 on Ubuntu 25.04beta. Both using Wayland.

**Comment by cringifyq** [comment]
Gnome 47 and older probably don't support that function, best solution to this is to change 

"this._tracker = global.backend.get_cursor_tracker(global.display);"
back to
"this._tracker = Meta.CursorTracker.get_for_display(global.display);"

and add "import Meta from 'gi://Meta';" before "import Clutter from 'gi://Clutter';" in cursor.js

**Comment by ApenasGabs** [comment]
I'm getting the same error 

**Error:** `TypeError: global.backend.get_cursor_tracker is not a function`  
**System:** Bazzite 41 (Silverblue), GNOME 47.4, Kernel 6.13.5, AMD Ryzen Z1 Extreme, AMD GPU (Phoenix1), 15 GiB RAM

**Comment by ApenasGabs** [comment]
> Gnome 47 and older probably don't support that function, best solution to this is to change
> 
> "this._tracker = global.backend.get_cursor_tracker(global.display);" back to "this._tracker = Meta.CursorTracker.get_for_display(global.display);"
> 
> and add "import Meta from 'gi://Meta';" before "import Clutter from 'gi://Clutter';" in cursor.js

Hey @cringifyq , just wanted to say thanks — your solution worked perfectly!

I went into ~/.local/share/gnome-shell/extensions/wiggle@mechtifs/cursor.js and made the changes you suggested. After restarting GNOME, the extension works great on my setup (GNOME 47.4 on Bazzite / Fedora Atomic).

Really appreciate the clear fix 🙌

**Comment by danielschwab** [comment]
I created a PR (https://github.com/mechtifs/wiggle/pull/19) for the suggested solution. 

@mechtifs can you please integrate the PR and release a new version so we all can use the extension again (without local fixes).

**Comment by injcristianrojas** [comment]
New version has been published in GNOME Extensions and the issue has been fixed.
